version: '3.9'

services:
  proxy:
    image: nginx
    container_name: ${PROJECT_NAME}-proxy
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "../proxy:/etc/nginx/templates"
      - "/etc/letsencrypt/:/etc/letsencrypt/"
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://backend:4000}
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://frontend:3000}
      BLOCKSCOUT_DOMAIN: ${BLOCKSCOUT_DOMAIN}
      STATS_DOMAIN: ${STATS_DOMAIN}
      VISUALIZER_DOMAIN: ${VISUALIZER_DOMAIN}
    ports:
      - target: 443
        published: ${PORT_PREFIX}443
      - target: 8080
        published: ${PORT_PREFIX}8080
      - target: 8081
        published: ${PORT_PREFIX}8081
