version: '3.9'

services:
  redis-db:
    image: 'redis:alpine'
    container_name: ${COMPOSE_PROJECT_NAME}-redis-db
    command: redis-server
    volumes:
      - ./${COMPOSE_PROJECT_NAME}-redis-data:/data
