version: '3.9'

services:
  user-ops-indexer:
    image: ghcr.io/blockscout/user-ops-indexer:${USER_OPS_INDEXER_DOCKER_TAG:-latest}
    pull_policy: always
    restart: always
    container_name: '${COMPOSE_PROJECT_NAME}-user-ops-indexer'
    environment:
      - RPC_URL=${L2_RPC_URL}
      - ENTRY_POINT=0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789
      - DATABASE_URL=postgresql://blockscout:ceWb1MeLBEeOIfk65gU8EjF8@db:5432/blockscout
      - PORT=8050
